const SK_ERR_NO_STATUS = 1005;
const SK_ERR_ABNORMAL  = 1006;
const SK_ERR_INTERAL   = 1011;
const SK_ERR_RESTART   = 1012;
const SK_ERR_TRY_LATER = 1013;


module.exports =
{
	SK_ERR_NO_STATUS,
	SK_ERR_ABNORMAL,
	SK_ERR_INTERAL,
	SK_ERR_RESTART,
	SK_ERR_TRY_LATER,
};
